### ISSUE TITLE
ListFolderLongpoll error

### ISSUE THREAD

**Issue by alemigo** [dropbox/dropbox-sdk-rust#15]
Getting the following error when calling files::list_folder_longpoll:

"Dropbox API indicated that the request was malformed: Error in call to API function "files/list_folder/longpoll": Your request includes an Authorization header, but this function does not use it."

Dropbox API docs confirm that there is no authentication needed for this call.
https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder-longpoll 
                    
```
let args = files::ListFolderLongpollArg::new(cursor);
let result = match files::list_folder_longpoll(&client, &args) {
 error handling ......
```

**Comment by wfraser** [comment]
Good catch, this is currently the only no-auth route in the API, and because this SDK hasn't implemented support for different auth contexts yet, it is incorrectly adding an authorization header when it shouldn't.

I'll work on implementing some minimal support for different auth types so that this can work.
